# Generated by Django 2.2.2 on 2020-07-01 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahj_gis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='AHJID',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='county',
            name='AHJID',
            field=models.UUIDField(null=True),
        ),
    ]
