# Generated by Django 2.2.2 on 2020-07-01 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('ahj_gis', '0002_auto_20200701_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='AHJID',
        ),
        migrations.AddField(
            model_name='city',
            name='AHJ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.AHJ', to_field='AHJID'),
        ),
        migrations.AddField(
            model_name='county',
            name='AHJ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.AHJ', to_field='AHJID'),
        ),
    ]
