# Generated by Django 2.2.2 on 2020-07-02 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahj_gis', '0004_auto_20200701_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='STATEABBR',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='county',
            name='STATEABBR',
            field=models.CharField(default='', max_length=2),
        ),
    ]
