# Generated by Django 2.2.2 on 2020-07-02 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ahj_gis', '0005_auto_20200702_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='county',
            name='AHJID',
        ),
    ]
