# Generated by Django 2.2.2 on 2020-07-07 23:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahj_gis', '0006_remove_county_ahjid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STATEFP', models.CharField(max_length=2)),
                ('STATEABBR', models.CharField(default='', max_length=2)),
                ('POLYFP', models.CharField(max_length=5)),
                ('POLYNS', models.CharField(max_length=8)),
                ('GEOID', models.CharField(max_length=7)),
                ('NAME', models.CharField(max_length=100)),
                ('NAMELSAD', models.CharField(max_length=100)),
                ('LSAD', models.CharField(max_length=2)),
                ('CLASSFP', models.CharField(max_length=2)),
                ('MTFCC', models.CharField(max_length=5)),
                ('FUNCSTAT', models.CharField(max_length=1)),
                ('ALAND', models.BigIntegerField()),
                ('AWATER', models.BigIntegerField()),
                ('INTPTLAT', models.CharField(max_length=11)),
                ('INTPTLON', models.CharField(max_length=12)),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('CSAFP', models.CharField(default='', max_length=3)),
                ('CBSAFP', models.CharField(default='', max_length=5)),
                ('METDIVFP', models.CharField(default='', max_length=5)),
                ('PCICBSA', models.CharField(default='', max_length=1)),
                ('PCINECTA', models.CharField(default='', max_length=1)),
            ],
        ),
    ]
