# Generated by Django 2.2.2 on 2020-07-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahj_gis', '0007_polygon'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REGION', models.CharField(max_length=2)),
                ('STATEABBR', models.CharField(max_length=2)),
                ('DIVISION', models.CharField(max_length=2)),
                ('STATEFP', models.CharField(max_length=2)),
                ('STATENS', models.CharField(max_length=8)),
                ('GEOID', models.CharField(max_length=2)),
                ('STUSPS', models.CharField(max_length=2)),
                ('NAME', models.CharField(max_length=100)),
                ('LSAD', models.CharField(max_length=2)),
                ('MTFCC', models.CharField(max_length=5)),
                ('FUNCSTAT', models.CharField(max_length=1)),
                ('ALAND', models.BigIntegerField()),
                ('AWATER', models.BigIntegerField()),
                ('INTPTLAT', models.CharField(max_length=11)),
                ('INTPTLON', models.CharField(max_length=12)),
            ],
        ),
    ]
