# Generated by Django 2.2.2 on 2020-07-09 21:44

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ahj_gis', '0009_auto_20200709_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='mpoly',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
            preserve_default=False,
        ),
    ]
