# Generated by Django 2.2.2 on 2020-10-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahj_gis', '0011_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygon',
            name='STATEABBR',
            field=models.CharField(db_index=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='state',
            name='STATEABBR',
            field=models.CharField(db_index=True, default='', max_length=2),
        ),
    ]
