# Generated by Django 2.2.2 on 2020-07-01 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ahj_gis', '0004_auto_20200701_2357'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahj',
            name='city_mpoly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ahj_gis.City'),
        ),
        migrations.AddField(
            model_name='ahj',
            name='county_mpoly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ahj_gis.County'),
        ),
        migrations.AddField(
            model_name='historicalahj',
            name='city_mpoly',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ahj_gis.City'),
        ),
        migrations.AddField(
            model_name='historicalahj',
            name='county_mpoly',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ahj_gis.County'),
        ),
    ]
