# Generated by Django 2.2.2 on 2020-07-08 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200708_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='AHJEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChangeType', models.CharField(max_length=45)),
                ('FieldName', models.CharField(max_length=45)),
                ('Value', models.TextField()),
                ('PreviousValue', models.CharField(max_length=255)),
                ('ModifyingUserID', models.IntegerField()),
                ('ModifiedDate', models.DateTimeField()),
                ('IsConfirmed', models.BooleanField(default=False)),
                ('ConfirmingUserID', models.IntegerField(default=None)),
                ('ConfirmedDate', models.DateTimeField(default=None)),
                ('VoteRating', models.IntegerField(default=0)),
                ('AHJ', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.AHJ', to_field='AHJID')),
            ],
        ),
    ]
