# Generated by Django 2.2.2 on 2020-07-08 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ahjedit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ahjedit',
            old_name='AHJ',
            new_name='Record',
        ),
    ]
