# Generated by Django 2.2.2 on 2020-07-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200708_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ahjedit',
            old_name='ChangeType',
            new_name='EditType',
        ),
        migrations.AlterField(
            model_name='ahj',
            name='WindCode',
            field=models.CharField(blank=True, choices=[('ASCE716', 'ASCE7-16'), ('ASCE710', 'ASCE7-10'), ('ASCE705', 'ASCE7-05'), ('SpecialWindZone', 'Special Wind Zone')], default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='ahjedit',
            name='PreviousValue',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='historicalahj',
            name='WindCode',
            field=models.CharField(blank=True, choices=[('ASCE716', 'ASCE7-16'), ('ASCE710', 'ASCE7-10'), ('ASCE705', 'ASCE7-05'), ('SpecialWindZone', 'Special Wind Zone')], default='', max_length=45),
        ),
    ]
