# Generated by Django 2.2.2 on 2020-07-08 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200708_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RecordID', models.CharField(max_length=45)),
                ('RecordType', models.CharField(max_length=45)),
                ('EditType', models.CharField(max_length=45)),
                ('FieldName', models.CharField(max_length=45)),
                ('Value', models.TextField()),
                ('PreviousValue', models.TextField()),
                ('ModifyingUserID', models.IntegerField()),
                ('ModifiedDate', models.DateTimeField()),
                ('IsConfirmed', models.BooleanField(default=False)),
                ('ConfirmingUserID', models.IntegerField(default=None)),
                ('ConfirmedDate', models.DateTimeField(default=None)),
                ('VoteRating', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='AHJEdit',
        ),
    ]
