# Generated by Django 2.2.2 on 2020-07-10 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200710_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit',
            name='ConfirmedDate',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='edit',
            name='ConfirmingUserID',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
