# Generated by Django 2.2.2 on 2020-07-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_edit_parentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='edit',
            name='ParentRecordType',
            field=models.CharField(default='', max_length=45),
        ),
    ]
