# Generated by Django 2.2.2 on 2020-07-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_edit_parentrecordtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit',
            name='IsConfirmed',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='edit',
            name='ModifiedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
