# Generated by Django 2.2.2 on 2020-07-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200713_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit',
            name='PreviousValue',
            field=models.TextField(default=None, null=True),
        ),
    ]
