# Generated by Django 2.2.2 on 2020-07-21 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200717_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VotingUserID', models.IntegerField()),
                ('VoteType', models.CharField(default='', max_length=10)),
                ('Edit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Edit')),
            ],
        ),
    ]
