# Generated by Django 2.2.2 on 2020-07-21 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200721_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='VoteType',
            new_name='Rating',
        ),
    ]
