# Generated by Django 2.2.2 on 2020-08-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_user_ahj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit',
            name='Value',
            field=models.TextField(blank=True, default=''),
        ),
    ]
