# Generated by Django 2.2.2 on 2020-08-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200812_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit',
            name='PreviousValue',
            field=models.TextField(blank=True, default=''),
        ),
    ]
