# Generated by Django 2.2.2 on 2020-09-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200820_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahj',
            name='AHJCode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ahj',
            name='AHJLevelCode',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='historicalahj',
            name='AHJCode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='historicalahj',
            name='AHJLevelCode',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
