# Generated by Django 2.2.2 on 2020-09-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20200904_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahj',
            name='DataSourceComments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalahj',
            name='DataSourceComments',
            field=models.TextField(blank=True),
        ),
    ]
