# Generated by Django 2.2.2 on 2021-01-22 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20200906_0355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engineeringreviewrequirement',
            old_name='RequirementLevelNotes',
            new_name='RequirementNotes',
        ),
        migrations.RenameField(
            model_name='historicalengineeringreviewrequirement',
            old_name='RequirementLevelNotes',
            new_name='RequirementNotes',
        ),
        migrations.RemoveField(
            model_name='ahj',
            name='DocumentSubmissionMethod',
        ),
        migrations.RemoveField(
            model_name='historicalahj',
            name='DocumentSubmissionMethod',
        ),
        migrations.AddField(
            model_name='ahj',
            name='EstimatedTurnaroundDays',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ahj',
            name='PermitIssueMethodNotes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicalahj',
            name='EstimatedTurnaroundDays',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historicalahj',
            name='PermitIssueMethodNotes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='PermitIssueMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PermitIssueMethod', models.CharField(blank=True, choices=[('Epermitting', 'Epermitting'), ('Email', 'Email'), ('InPerson', 'In Person'), ('SolarApp', 'SolarAPP')], default='', max_length=45)),
                ('AHJ', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.AHJ', to_field='AHJID')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalFeeStructure',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('Description', models.TextField(blank=True)),
                ('FeeStructureID', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('FeeStructureName', models.CharField(blank=True, max_length=100)),
                ('FeeStructureType', models.CharField(blank=True, choices=[('Flat', 'Flat'), ('SystemSize', 'System Size')], default='', max_length=45)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('AHJ', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.AHJ', to_field='AHJID')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical fee structure',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(blank=True)),
                ('FeeStructureID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('FeeStructureName', models.CharField(blank=True, max_length=100)),
                ('FeeStructureType', models.CharField(blank=True, choices=[('Flat', 'Flat'), ('SystemSize', 'System Size')], default='', max_length=45)),
                ('AHJ', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.AHJ', to_field='AHJID')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSubmissionMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocumentSubmissionMethod', models.CharField(blank=True, choices=[('Epermitting', 'Epermitting'), ('Email', 'Email'), ('InPerson', 'In Person'), ('SolarApp', 'SolarAPP')], default='', max_length=45)),
                ('AHJ', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.AHJ', to_field='AHJID')),
            ],
        ),
        migrations.CreateModel(
            name='AHJInspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AHJInspectionName', models.CharField(blank=True, max_length=100)),
                ('AHJInspectionNotes', models.CharField(blank=True, max_length=255)),
                ('Description', models.TextField(blank=True)),
                ('FileFolderURL', models.CharField(blank=True, max_length=255)),
                ('InspectionType', models.CharField(blank=True, choices=[('RoughIn', 'Rough In'), ('Final', 'Final'), ('Windstorm', 'Windstorm'), ('Electrical', 'Electrical'), ('Structural', 'Structural')], default='', max_length=45)),
                ('TechnicianRequired', models.BooleanField(null=True)),
                ('AHJ', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.AHJ', to_field='AHJID')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='AHJInspection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.AHJInspection'),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='AHJInspection',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.AHJInspection'),
        ),
    ]
