webpageTokenUrls= [ 
    ('ahj-private', {}),
    ('single_ahj', {}),
    ('ahj-set-maintainer', {}), 
    ('ahj-remove-maintainer', {}), 
    #('edit-list', {}),
    #('edit-submit', {}), 
    ('create-api-token', {}), 
    #('edit-review', {}), 
    #('edit-update', {}), 
    #('edit-deletion', {}), 
    #('edit-addition', {}), 
    ('user-update', {'username':'test'}), 
    ('user-edits', {}), 
    ('user-comments', {}),
    ('active-user-info', {}), 
    ('single-user-info', {'username': 'test'}), 
    ('comment-submit', {}), 
    ('data-map', {}), 
    ('data-map-polygon', {}), 
    ('form-validator', {}), 
    ('user-create', {}), 
    ('user-login', {}),
    ('user-logout', {}), 
    #('unconfirmed-conts', {}), 
    #('unconfirmed-insps', {}), 
    ('create-chat-room', {}), 
    ('adjust-timestamp', {}),
]

apiTokenUrls = [
    ('ahj-public', {}), 
    ('ahj-geo-address', {}), 
    ('ahj-geo-location', {}), 
]