# Generated by Django 3.1.3 on 2021-05-11 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ahj_app', '0008_auto_20210430_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='edit',
            name='EditType',
            field=models.CharField(db_column='EditType', default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='ahjcontactrepresentative',
            name='ContactStatus',
            field=models.BooleanField(db_column='ContactStatus', null=True),
        ),
        migrations.AlterField(
            model_name='ahjdocumentsubmissionmethoduse',
            name='MethodStatus',
            field=models.BooleanField(db_column='MethodStatus', null=True),
        ),
        migrations.AlterField(
            model_name='ahjinspection',
            name='InspectionStatus',
            field=models.BooleanField(db_column='InspectionStatus', null=True),
        ),
        migrations.AlterField(
            model_name='ahjinspectioncontact',
            name='ContactStatus',
            field=models.BooleanField(db_column='ContactStatus', null=True),
        ),
        migrations.AlterField(
            model_name='ahjpermitissuemethoduse',
            name='MethodStatus',
            field=models.BooleanField(db_column='MethodStatus', null=True),
        ),
        migrations.AlterField(
            model_name='ahjusermaintains',
            name='MaintainerStatus',
            field=models.BooleanField(db_column='MaintainerStatus'),
        ),
        migrations.AlterField(
            model_name='edit',
            name='AHJPK',
            field=models.ForeignKey(db_column='AHJPK', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ahj_app.ahj'),
        ),
        migrations.AlterField(
            model_name='edit',
            name='NewValue',
            field=models.CharField(blank=True, db_column='NewValue', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='edit',
            name='OldValue',
            field=models.CharField(blank=True, db_column='OldValue', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='engineeringreviewrequirement',
            name='EngineeringReviewRequirementStatus',
            field=models.BooleanField(db_column='EngineeringReviewRequirementStatus', null=True),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='FeeStructureStatus',
            field=models.BooleanField(db_column='FeeStructureStatus', null=True),
        ),
    ]
