# Generated by Django 3.1.3 on 2021-05-12 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ahj_app', '0008_auto_20210430_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Photo',
            field=models.CharField(db_column='Photo', default='user-image/default.jpeg', max_length=255),
        ),
    ]
