# Generated by Django 3.1.3 on 2021-05-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahj_app', '0009_add_edit_table_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='edit',
            name='DataSourceComment',
            field=models.CharField(db_column='DataSourceComment', default='', max_length=255),
            preserve_default=False,
        ),
    ]
