# Generated by Django 3.1.3 on 2021-05-17 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ahj_app', '0009_auto_20210512_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='APICalls',
            field=models.IntegerField(db_column='NumAPICalls', default=0),
        ),
        migrations.CreateModel(
            name='SubscribedChannels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChannelID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('LastReadToken', models.CharField(max_length=255)),
                ('UserID', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('UserID', 'ChannelID')},
            },
        ),
    ]
