# Generated by Django 3.1.3 on 2021-07-18 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ahj_app', '0011_auto_20210623_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='SunspecAllianceMember',
            fields=[
                ('MemberID', models.AutoField(db_column='MemberID', primary_key=True, serialize=False)),
                ('MemberName', models.CharField(db_column='MemberName', max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SunspecAllianceMemberDomain',
            fields=[
                ('DomainID', models.AutoField(db_column='DomainID', primary_key=True, serialize=False)),
                ('Domain', models.CharField(db_column='Domain', max_length=254)),
                ('MemberID', models.ForeignKey(db_column='MemberID', on_delete=django.db.models.deletion.DO_NOTHING, to='ahj_app.sunspecalliancemember')),
            ],
        ),
        migrations.CreateModel(
            name='AHJOfficeDomain',
            fields=[
                ('DomainID', models.AutoField(db_column='DomainID', primary_key=True, serialize=False)),
                ('Domain', models.CharField(db_column='Domain', max_length=254)),
                ('AHJID', models.ForeignKey(db_column='AHJID', on_delete=django.db.models.deletion.DO_NOTHING, to='ahj_app.ahj')),
            ],
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='MemberID',
            field=models.ForeignKey(blank=True, db_column='MemberID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ahj_app.sunspecalliancemember'),
        ),
        migrations.AddField(
            model_name='user',
            name='MemberID',
            field=models.ForeignKey(db_column='MemberID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ahj_app.sunspecalliancemember'),
        ),
    ]
